### ISSUE TITLE
1. 获取所有年龄小于 18 岁的对象，并返回他们的名称和年龄

### ISSUE THREAD

**Issue by CatfishEffect** [CodingMeUp/some_notes#58]
你好，非常感谢博主，这篇文章教程使我获益匪浅。在使用 lodash 尝试解题的过程中遇到了问题，可以提供个 lodash 实现的教程参考吗

**Comment by CodingMeUp** [comment]
lodash这种没必要深入

**Comment by CatfishEffect** [comment]
在使用 lodash 实现的过程中遇到了占位符的问题。Ramda 中可以使用 "_" 作为占位符，lodash 遇到这种情况也有类似的吗

**Comment by CodingMeUp** [comment]
> 

这一块我不太了解诶 既然有解法了可以关注其他问题 或者看下他的源码是怎么实现的做个util 或者 polyfill

**Comment by CatfishEffect** [comment]
好的，谢谢你帮忙解答疑惑

**Comment by CodingMeUp** [comment]
·
